//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surpass.Utils.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Surpass.Utils.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 MIICXQIBAAKBgQDLes8aXq2afeQF2HcJ9C0HZfYnCIoJFINQaJYrKylxzdK/0mlf8au+awqiRIk//bqTyKSiCT/DZUq0vVTprxzCrNvaWGuxvgbTbjbTyMGEfQ9TTEHLggEJUxZvQrReXPGlmN/oGBwmTRQmmis3y19KqsdFGtNUYRHMyPui54nh+wIDAQABAoGAQmls2wB3zOq116qU/6ywXa/LrWW+F8SYL1BTYveNaVVyKaV1OxlXoqixKdEQstAPa1ibUz+NjiqrPV5mLnc2/UXFER8MLDDzEdej/rsTbiP0q3mbWEr3vbD+g9yO8WB/4ox7Qws6w55IxDyW2aBgD7y+Cf1zKBSHV+a3rN6YDBECQQDyxkLnijLPnqaC1UlfpN3Q7EV5/1g4gY+DdyN7FzstVUqpvER/cgX34gTiribkL+ER3H2eN1IzVy0A5r7zA6HlAkEA1pCK0zhYpL1Ozg+T8srSYz2nd0R2UsLNE7gJOUEaSc5YiT6AWyZ3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestRsaPraviteKey {
            get {
                return ResourceManager.GetString("TestRsaPraviteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDLes8aXq2afeQF2HcJ9C0HZfYnCIoJFINQaJYrKylxzdK/0mlf8au+awqiRIk//bqTyKSiCT/DZUq0vVTprxzCrNvaWGuxvgbTbjbTyMGEfQ9TTEHLggEJUxZvQrReXPGlmN/oGBwmTRQmmis3y19KqsdFGtNUYRHMyPui54nh+wIDAQAB 的本地化字符串。
        /// </summary>
        internal static string TestRsaPublicKey {
            get {
                return ResourceManager.GetString("TestRsaPublicKey", resourceCulture);
            }
        }
    }
}
