//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Surpass.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Surpass.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 参数{0}值为 null。 的本地化字符串。
        /// </summary>
        internal static string ArgumentNullErrorMessage {
            get {
                return ResourceManager.GetString("ArgumentNullErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数{0}值为空白字符。 的本地化字符串。
        /// </summary>
        internal static string ArgumentWhiteSpaceErrorMessage {
            get {
                return ResourceManager.GetString("ArgumentWhiteSpaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在重复的 Key。 的本地化字符串。
        /// </summary>
        internal static string KeyRepeatErrorMessage {
            get {
                return ResourceManager.GetString("KeyRepeatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 不是基本类型时，必须是类类型。 的本地化字符串。
        /// </summary>
        internal static string NotBaseTypeNotEqualClass {
            get {
                return ResourceManager.GetString("NotBaseTypeNotEqualClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 不是基本类型。 的本地化字符串。
        /// </summary>
        internal static string NotEqualBaseType {
            get {
                return ResourceManager.GetString("NotEqualBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 必须是类或接口类型才能支持实例委托。 的本地化字符串。
        /// </summary>
        internal static string NotEqualClassOrInterfaceNotSupportedDelegate {
            get {
                return ResourceManager.GetString("NotEqualClassOrInterfaceNotSupportedDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的表达式 {0}。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedExpression {
            get {
                return ResourceManager.GetString("NotSupportedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的类型 {0}。 的本地化字符串。
        /// </summary>
        internal static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只读字典不支持 {0} 操作。 的本地化字符串。
        /// </summary>
        internal static string ReadOnlyNotSupportedOperation {
            get {
                return ResourceManager.GetString("ReadOnlyNotSupportedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 无默认的公共构造函数。 的本地化字符串。
        /// </summary>
        internal static string TypeNotDefaultConstructor {
            get {
                return ResourceManager.GetString("TypeNotDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 {0} 不是类型 {1} 的实例分配。 的本地化字符串。
        /// </summary>
        internal static string TypeNotTypeAssignableFrom {
            get {
                return ResourceManager.GetString("TypeNotTypeAssignableFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的  Ldc_I 值 {0} 。 的本地化字符串。
        /// </summary>
        internal static string UnknownLdcId {
            get {
                return ResourceManager.GetString("UnknownLdcId", resourceCulture);
            }
        }
    }
}
